config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  root "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :games, only: %i[index new create] do # /games GET user-games index, /games/new GET games new, /game/new POST games create
    resources :users_games, only: %i[new create edit update]
    resources :teams, only: [:index]
    resources :matches, only: [:index] do
      resources :pronostics, only: %i[create update]
    end
    member do
      get :dashboard
      get :ranking
#       get :join
    end
  end

  namespace :admin do 
    resources :matches, only: [:index, :new, :create, :edit, :update]
  end

  namespace :organisateur do
    resources :games, only: [:edit] do # /organisateur/games/edit
      resources :departments, only: [:create]
    end
  end
  
  resources :chats, only: :show do
    resources :messages, only: [:create]
  end

  get 'join_game/:code', to: 'games#join', as: :join_game
  get '/games/check_code', to: 'games#check_code', as: 'games_check_code'
  get '/games/change_game', to: 'games#change', as: :change_game

end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team, class_name: 'Team'
  belongs_to :away_team, class_name: 'Team'
  has_many :pronostics, dependent: :destroy
  STAGES = ["phase de groupes", "huitième de finale", "quart de finale", "demi-finale", "finale"]
end

app/controllers/admin/matches_controller.rb
class Admin::MatchesController < ApplicationController

    def index
        @matches = Match.all
    end
    
    def new
      @match = Match.new
    end

    def create
      @match = Match.new(match_params)
      if @match.save
        redirect_to admin_matches_path, notice: 'Match créé avec succès'
      else
        render :new
      end
    end

    def update
        @match = Match.find(params[:id])
        if @match.update(match_params)
          redirect_to :admin_matches, notice: 'Match mis à jour avec succès.'
          increment = IncrementTotalScore.new(@match)
          increment.matchWinner
          increment.updatePronoStatus
          increment.finalWinner if @match.stage == 'finale'
        else
          render :edit
        end
    end

    private

    def match_params
        params.require(:match).permit(:stage, :date, :home_team_id, :away_team_id, :home_team_result, :away_team_result)
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def index
        @game = Game.find(params[:game_id])
        @matchs = Match.all
        @user = current_user
        @pronos = Pronostic.where(user: current_user, game: @game )
        @prono = Pronostic.new
        @matchs_2024_06_14 = Match.where("DATE(date) = ?", Date.parse('2024-06-14'))
        @matchs_2024_06_15 = Match.where("DATE(date) = ?", Date.parse('2024-06-15'))
        @matchs_2024_06_16 = Match.where("DATE(date) = ?", Date.parse('2024-06-16'))
        @matchs_2024_06_17 = Match.where("DATE(date) = ?", Date.parse('2024-06-17'))
        @matchs_2024_06_18 = Match.where("DATE(date) = ?", Date.parse('2024-06-18'))
        @matchs_2024_06_19 = Match.where("DATE(date) = ?", Date.parse('2024-06-19'))
        @matchs_2024_06_20 = Match.where("DATE(date) = ?", Date.parse('2024-06-20'))
        @matchs_2024_06_21 = Match.where("DATE(date) = ?", Date.parse('2024-06-21'))
        @matchs_2024_06_22 = Match.where("DATE(date) = ?", Date.parse('2024-06-22'))
        @matchs_2024_06_23 = Match.where("DATE(date) = ?", Date.parse('2024-06-23'))
        @matchs_2024_06_24 = Match.where("DATE(date) = ?", Date.parse('2024-06-24'))
        @matchs_2024_06_25 = Match.where("DATE(date) = ?", Date.parse('2024-06-25'))
        @matchs_2024_06_26 = Match.where("DATE(date) = ?", Date.parse('2024-06-26'))
        @matchs_2024_06_29 = Match.where("DATE(date) = ?", Date.parse('2024-06-29'))
        @matchs_2024_06_30 = Match.where("DATE(date) = ?", Date.parse('2024-06-30'))
        @matchs_2024_07_01 = Match.where("DATE(date) = ?", Date.parse('2024-07-01'))
        @matchs_2024_07_02 = Match.where("DATE(date) = ?", Date.parse('2024-07-02'))
        @matchs_2024_07_05 = Match.where("DATE(date) = ?", Date.parse('2024-07-05'))
        @matchs_2024_07_06 = Match.where("DATE(date) = ?", Date.parse('2024-07-06'))
        @matchs_2024_07_09 = Match.where("DATE(date) = ?", Date.parse('2024-07-09'))
        @matchs_2024_07_10 = Match.where("DATE(date) = ?", Date.parse('2024-07-10'))
        @matchs_2024_07_14 = Match.where("DATE(date) = ?", Date.parse('2024-07-14'))

    end
end

app/views/admin/matches/index.html.erb
<div class="container mt-5">
    <div class="page-title mt-5">
        <h1 class="prono-title">Scores à encoder</h1>
    </div>
    <div class="d-flex mt-3">
    <%= link_to "Nouveau match", new_admin_match_path, class: "btn signin-btn" %>
    </div>
    <div class="matches">
                <% @matches.each do |match| %>
                    <%= render "shared/match-result", match: match %>
                <% end %>
    </div>
</div>

app/views/admin/matches/new.html.erb
<div class="container">
  <div class="party">
    <h2>Créer une nouveau match</h2>
    <%= simple_form_for [:admin, @match] do |f| %>
      <%= f.input :stage, collection: Match::STAGES %>
      <%= f.input :date, as: :datetime %>
      <%# <%= f.input :date, as: :datetime_select %>
      <%= f.input :home_team_id, collection: Team.all, label_method: :name, value_method: :id, prompt: "Sélectionner l'équipe à domicile" %>
      <%= f.input :away_team_id, collection: Team.all, label_method: :name, value_method: :id, prompt: "Sélectionner l'équipe à l'extérieur" %>
      <%# <%= f.input :date, as: :datetime_picker %>    
      <%= button_tag type: 'submit', id: "newmatch" do %>
        <i class="fa-regular fa-square-plus" aria-hidden="true"></i> Créer le match
      <% end %>
    <% end %>
  </div>
</div>