config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  root "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :games, only: %i[index new create] do # /games GET user-games index, /games/new GET games new, /game/new POST games create
    resources :users_games, only: %i[new create edit update]
    resources :teams, only: [:index]
    resources :matches, only: [:index] do
      resources :pronostics, only: %i[create update]
    end
    member do
      get :dashboard
      get :ranking
#       get :join
    end
  end

  namespace :admin do 
    resources :matches, only: [:index, :new, :create, :edit, :update]
  end

  namespace :organisateur do
    resources :games, only: [:edit] do # /organisateur/games/edit
      resources :departments, only: [:create]
    end
  end
  
  resources :chats, only: :show do
    resources :messages, only: [:create]
  end

  get 'join_game/:code', to: 'games#join', as: :join_game
  get '/games/check_code', to: 'games#check_code', as: 'games_check_code'
  get '/games/change_game', to: 'games#change', as: :change_game

end

app/views/shared/_cookies.html.erb
<%# <div class="alert alert-dismissible alert-warning text-center cookie-alert" role="alert">
  Ce site utilise des cookies pour vous offrir la meilleure expérience utilisateur. En continuant à naviguer sur ce site, vous acceptez notre utilisation des cookies. <a href="/politique-de-confidentialite" class="alert-link">En savoir plus</a>.
  <button type="button" class="btn btn-primary btn-sm accept-cookies">Accepter</button>
</div> %>
<%# 
<div class="flash flash-popup alert alert-dismissible fade show fixed-bottom" role="alert" data-controller="fade-out" id="flash-alert">
  <span> Ce site utilise des cookies pour vous offrir la meilleure expérience utilisateur. En continuant à naviguer sur ce site, vous acceptez notre utilisation des cookies. </span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div> %>

app/views/shared/_edit-game.html.erb
<div class="team-form">
    <%= simple_form_for @department, url: organisateur_game_departments_path(@game) do |f| %>
        <div>
            <%= f.input :name, label: false, placeholder: "Nom d'équipe" %>
        </div>
        <div class="validation">
            <%= f.button :submit, 'Créer', data: {action: 'click->newteam#display'}, class: "btn-test" %>
        </div>
    <% end %>
</div>

app/views/shared/_final-winner-form.html.erb
<div class="container">
    <%= simple_form_for([@game, @user_game], url: game_users_game_path(@game, @user_game)) do |f| %>
        <div class="final-winner">
            <%= f.label :final_winner_id, "Equipe championne ?", class: "mb-2" %>
            <%= f.collection_select :final_winner_id, Team.all, :id, :name, class: "form-select", prompt: "Choisis une équipe" %>
        </div>
    <div class="actions">
        <%= f.submit "Valider", class: "btn btn signin-btn" %>
    </div>
    <% end %>
</div>


app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# <div class="footer-links">
  <div class="footer-text">
  SUIVEZ-NOUS
  </div>
  <div class="links-icon"></div>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="footer-copyright">
    Made with <i class="fas fa-heart"></i> by TEAMTIES team
  </div>
</div>

app/views/shared/_match-result-form.html.erb
<div>
    <%= simple_form_for(match, url: admin_match_path(match)) do |f| %>
        <div class="input-prono">
            <%= f.input :home_team_result, :input_html => { :type => 'text', :inputmode => 'numeric' }, class: "result", label: false %>
            <%= f.input :away_team_result, :input_html => { :type => 'text', :inputmode => 'numeric' }, class: "result", label: false %>
        </div>
        <div class="validation">
            <%= f.button :submit, 'Valider' %>
        </div>
    <% end %>
</div>

app/views/shared/_match-result.html.erb
<% if match.home_team_result.nil? %>
<div class="match-result">
    <div class="home-team">
        <div class="flag flag-left">
            <img src="<%= match.home_team.flag %>" alt="<%= match.home_team.name %> Flag">
        </div>
        <div class="team-name">
            <%= match.home_team.name %>
        </div>
        <div class="shape">
        </div>
    </div>
    <div class="score">
        <div class="group text-center mb-2">
            <% unless match.date.nil?%>
            <%= match.date.strftime("%d-%m") %>
            <% end %>
        </div>
        <div class="group text-center mb-2">
            Groupe <%= match.group %>
        </div>
        <div class="prono">
                <%= render "shared/match-result-form", match: match%>
        </div>
    </div>
    <div class="away-team">
        <div class="flag flag-right">
            <img src="<%= match.away_team.flag %>" alt="<%= match.away_team.name %> Flag">
        </div>
        <div class="team-name">
            <%= match.away_team.name %>
        </div>
        <div class="shape">
        </div>
    </div>
</div>
<% end  %>

app/views/shared/_match.html.erb
<div class="match">
    <div class="home-team">
        <div class="flag flag-left">
            <img src="<%= match.home_team.flag %>" alt="<%= match.home_team.name %> Flag">
        </div>
        <div class="team-name">
            <%= match.home_team.name %>
        </div>
        <div class="shape">
        </div>
    </div>
    <div class="score">
        <div class="group text-center mb-2">
            <% unless match.group.nil? %>
            Groupe <%= match.group %>
            <% end %>
        </div>
        <div class="prono">
            <div class="monprono">Mon prono :</div>
            <%# L'encodage de prono n'est possible que jusqu'à 10min avant le début du match %>
            <% if ((match.date - Time.now) >= 130*60)  && !@dashboard %>
              <div>
                <%= render "shared/my-prono-form", match: match, prono: prono.nil? ? Pronostic.new : prono %>
              </div>
            <% elsif   %>
                <div class="input-prono">
                    <div class="team-prono form-control">
                        <%= prono.home_team_prono unless prono.nil? %>
                    </div>
                    <div class="team-prono form-control">
                        <p><%= prono.away_team_prono unless prono.nil? %></p>
                    </div>
                </div>
            <% elsif @dashboard %>
              <div>
                <%= render "shared/my-prono-form-readonly", match: match, prono: @prono %>
              </div>
            <% end %>
            <% if match.home_team_result.nil? %>
                <div class="hour">
                    <%= match.date.strftime("%H:%M") %>
                </div>
            <% else %>
                <div class="result">
                    <div class="final-result">Score final <%= match.home_team_result %> - <%= match.away_team_result %></div>
                    <div class="final-points">
                    <% unless prono.nil? %>
                        <% if match.stage == 'phase de groupes' %>
                            <% if prono.status == 'bonus' %>
                                + 3 
                            <% elsif prono.status == 'win'%>
                                + 1
                            <% end %>
                        <% else %>
                            <% if prono.status == 'bonus' %>
                                + 4 
                            <% elsif prono.status == 'win'%>
                                + 2
                            <% end %>
                        <% end %>
                    <% end %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <div class="away-team">
        <div class="flag flag-right">
            <img src="<%= match.away_team.flag %>" alt="<%= match.away_team.name %> Flag">
        </div>
        <div class="team-name">
            <%= match.away_team.name %>
        </div>
        <div class="shape">
        </div>
    </div>
</div>

app/views/shared/_my-prono-form-readonly.html.erb
<div>
  <%= simple_form_for [@game, match, prono || Pronostic.new] do |f| %>
    <div class="input-prono">
      <% if prono %>
        <%= f.input :home_team_prono, :input_html => { :type => 'text', :inputmode => 'numeric' }, label: false %>
        <%= f.input :away_team_prono, :input_html => { :type => 'text', :inputmode => 'numeric' }, label: false, disabled: true %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_my-prono-form.html.erb
<div>
    <%= simple_form_for [@game, match, prono], html: { data: { controller: "auto-save-prono" } } do |f| %>
        <div class="input-prono">
            <%= f.input :home_team_prono, :input_html => { :type => 'text', :inputmode => 'numeric', data: {action: 'input->auto-save-prono#submit', auto_save_prono_target: "input" } }, label: false %>
            <%= f.input :away_team_prono, :input_html => { :type => 'text', :inputmode => 'numeric', data: {action: 'input->auto-save-prono#submit', auto_save_prono_target: "input" } }, label: false %>
        </div>
        <div class="validation">
            <% f.button :submit, 'Valider' %>
        </div>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class: "logo" %>
    <% end %>
    <h1 class="teamties">TEAMTIES</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "HOME", root_path, class: "nav-link navbar-font" %>
          </li>
          <% if !@game.nil? && @game.persisted? %>
          <li class="nav-item">
            <%= link_to "DASHBOARD", dashboard_game_path(@game), class: "nav-link navbar-font" %>
          </li>
          <li class="nav-item" style="width: 242px;">
            <!-- espace vide -->
          </li>
          <li class="nav-item">
            <%= link_to "PRONOS", game_matches_path(@game), class: "nav-link navbar-font" %>
          </li>
          <li class="nav-item">
            <%= link_to "CLASSEMENT", ranking_game_path(@game), class: "nav-link navbar-font" %>
          </li>
          <li class="nav-item">
            <% if @game.chat.nil? %>
              <p></p>
            <% else %>
              <%= link_to chat_path(@game.chat), class: "nav-link navbar-font" do %>
                 <i class="fa-regular fa-comment-dots"></i> CHAT
              <% end %>
            <% end %>
          </li>
          <% else %>
          <!-- Afficher les liens vers les autres onglets même si @game.chat est nil -->
          <li class="nav-item">
            <%= link_to "DASHBOARD", root_path, class: "nav-link navbar-font" %>
          </li>
          <li class="nav-item">
            <%= link_to "PRONOS", root_path, class: "nav-link navbar-font" %>
          </li>
          <li class="nav-item">
            <%= link_to "CLASSEMENT", root_path, class: "nav-link navbar-font" %>
          </li>
          <% end %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag url_for(current_user.avatar), class: "avatar-large", alt: "avatar dropdown menu" %>
              <% else %>
                <%= image_tag "1824147.svg", class: "avatar-large", alt: "avatar dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Editer mon profil", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Changer de partie", change_game_path, class: "dropdown-item" %>
              <% if current_user.admin? %>
              <%= link_to "Admin",  admin_matches_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
  <%= link_to 'TEAMTIES', root_path, class: 'navbar-brand teamties' %>
  <button class="navbar-toggler me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarOffcanvasLg" aria-controls="navbarOffcanvasLg" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="offcanvas offcanvas-end" tabindex="-1" id="navbarOffcanvasLg" aria-labelledby="navbarOffcanvasLgLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">MENU</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body align-items-center">
        <ul class="navbar-nav justify-content-around flex-grow-1 pe-3">
            <% if user_signed_in? %>

                <li class="nav-item active">
                    <%= link_to "ACCUEIL", root_path, class: "nav-link navbar-font" %>
                </li>

                <% if !@game.nil? && @game.persisted? %>

                    <li class="nav-item">
                        <%= link_to "DASHBOARD", dashboard_game_path(@game), class: "nav-link navbar-font" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "PRONOS", game_matches_path(@game), class: "nav-link navbar-font" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to "CLASSEMENT", ranking_game_path(@game), class: "nav-link navbar-font" %>
                    </li>

                    <li class="nav-item">
                        <%= link_to chat_path(@game.chat), class: "nav-link navbar-font" do %>
                        <i class="fa-regular fa-comment-dots"></i> CHAT
                        <% end %>
                    </li>

                    <% if (current_user.users_games.count > 1) %>

                        <li class="nav-item dropdown">
                            <a class="nav-link navbar-font dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            MES PARTIES
                            </a>
                            <ul class="dropdown-menu">
                                <% current_user.games.each do |game|  %>
                                 <li><%= link_to dashboard_game_path(game), class: "dropdown-item" do %>
                                    <%= game.name %>
                                    <% end %>
                                 </li>
                                <% end  %>
                            </ul>
                        </li>

                    <% end %>

                <% end %>
        </ul>
        <ul class="navbar-nav justify-content-end pe-3">
            <li class="nav-item dropdown d-flex justify-content-center">
                <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.avatar.attached? %>
                    <%= image_tag url_for(current_user.avatar), class: "avatar-large", alt: "avatar dropdown menu" %>
                <% else %>
                    <%= image_tag "1824147.svg", class: "avatar-large", alt: "avatar dropdown menu" %>
                <% end %>
                </a>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Editer mon profil", edit_user_registration_path, class: "dropdown-item" %>
                <% if current_user.admin? %>
                <%= link_to "Admin",  admin_matches_path, class: "dropdown-item" %>
                <% end %>
                <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </div>
            </li>
        </ul>
            <% else %>
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: "nav-link navbar-font" %>
                </li>
            </ul>
            <% end %>
       
        
      </div>
    </div>
</nav>

app/views/shared/_popup.html.erb
<%# <div class="flash flash-popup alert alert-dismissible fade show" role="alert" data-controller="fade-out" id="flash-alert">
  <span> Rends-toi vite sur la page <strong>'Mes Pronos'</strong> pour les compléter !&nbsp;&nbsp;&nbsp;&nbsp;</span>
  <a data-bs-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div> %>

app/views/shared/_ranking.html.erb
  <div class="podium-container">
    <div class="podium-ind">
      <div class="podium-category-ind">
        <h2 class="title-podium-cat">PODIUM INDIVIDUEL</h2>
        <div class="podium-table">
          <table>
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">PSEUDO</th>
                <th scope="col">EQUIPE</th>
                <th scope="col">POINTS</th>
              </tr>
            </thead>
            <tbody>
              <% if @dashboard_individual_rankings.present? %>
                <% @dashboard_individual_rankings.each_with_index do |a, index| %>
                  <tr>
                    <th scope="row"><%= index + 1 %></th>
                    <td><%= a.respond_to?(:pseudo) ? a.pseudo : a[0] %></td>
                    <td><%= a.team %></td>
                    <td><%= a.total_score %></td>
                  </tr>
                <% end %>
              <% else %>
                <tr>
                  <td colspan="3">Aucune donnée de classement n'est disponible pour le moment.</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>


    <div class="podium-category-col">
      <h2 class="title-podium-cat">PODIUM COLLECTIF</h2>
      <div class="podium-table">
        <table>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">EQUIPE</th>
              <th scope="col">POINTS</th>
            </tr>
          </thead>
          <tbody>
            <% @dashboard_department_rankings.each_with_index do |ranking, index| %>
              <tr>
                <th scope="row"><%= index + 1 %></th>
                <td><%= ranking.team %></td>
                <td><%= ranking.average_score %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>