config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  root "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :games, only: %i[index new create] do # /games GET user-games index, /games/new GET games new, /game/new POST games create
    resources :users_games, only: %i[new create edit update]
    resources :teams, only: [:index]
    resources :matches, only: [:index] do
      resources :pronostics, only: %i[create update]
    end
    member do
      get :dashboard
      get :ranking
#       get :join
    end
  end

  namespace :admin do 
    resources :matches, only: [:index, :new, :create, :edit, :update]
  end

  namespace :organisateur do
    resources :games, only: [:edit] do # /organisateur/games/edit
      resources :departments, only: [:create]
    end
  end
  
  resources :chats, only: :show do
    resources :messages, only: [:create]
  end

  get 'join_game/:code', to: 'games#join', as: :join_game
  get '/games/check_code', to: 'games#check_code', as: 'games_check_code'
  get '/games/change_game', to: 'games#change', as: :change_game

end

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1> %>
<%# <p>Find me in app/views/pages/home.html.erb</p> %>
<div class="home-ban">
  <div class="home-img"></div>
      <div class="home-degrade">
        <div class="word-ban">
          <h1 class="first-word">Parier</h1>
          <h1 id="second-word">s'amuser</h1>
          <div class="p-ban">
          <p id="text-white">Plongez dans l'excitation de l'EURO 2024 avec "Team Ties", notre application dédiée aux paris entre collègues ! Que vous soyez un amateur passionné de football ou un novice curieux, rejoignez-nous pour une expérience de paris fun et conviviale.</p>
          <%= link_to(new_game_path, class: "btn btn-left") do %>
            <i class="fa-regular fa-square-plus"></i> Créer une partie
            <% end %>
          <%= link_to(games_check_code_path, class: "btn btn-right") do %>
          <i class="fa-solid fa-arrow-right-to-bracket"></i> Rejoindre une partie
          <% end %>
          </div>
        </div>
      </div>
      </div>
    <div class="infos">
    <div class ="infos-img">
    <img src="https://static.vecteezy.com/ti/vecteur-libre/p1/22700816-euro-2024-allemagne-officiel-logo-avec-nom-symbole-europeen-football-final-conception-illustration-vecteur-avec-retour-contexte-gratuit-vectoriel.jpg" class="uefa-img"/></div>
    <div class="text-infos">
      <h1>EURO 2024 de football</h1>
      <p>L'Euro 2024 de football est un tournoi européen majeur qui se déroule tous les quatre ans. Pour cette édition,
      l'Allemagne a été choisie comme pays hôte. Le tournoi rassemble les meilleures équipes nationales européennes qui
      s'affrontent pour remporter le titre de champion d'Europe. Les matches sont disputés dans plusieurs villes à travers
      le pays hôte. L'Euro 2024 est une compétition très attendue qui attire l'attention des amateurs de football du monde entier.
      </p>
    </div>
    </div>
    <div class="infos">
    <div class="text-infos">
    <h1 class="text-end">Team Ties - Le principe</h1>
      <p class="text-end">
        Le jeu de pronostic Team Ties a été créé par 4 "étudiants" dans le cadre de leur formation
        "Le Wagon - Développement Web" dispensée au cours des mois de février et mars 2024. Cette application a pour
        objectif principal de permettre aux gens de créer du lien et stimuler des interactions au sein d'une entreprise ou, tout simplement, un groupe d'amis.
      </p>
    </div>
    <div class="infos-img">
    <%= image_tag "logo.png", class: "uefa-img" %>
    </div>
    </div>

<div class="rules">
    <h1>Team Ties - Règles du Jeu</h1>
        <ol>
            <li><i class="fa-solid fa-circle-user"></i><strong>Inscription :</strong>
                <ul>
                    <li>Les participants doivent s'inscrire sur TeamTies avant le début de l'EURO 2024.</li>
                    <li>Chaque participant doit créer un compte avec un pseudonyme et rejoindre une équipe.</li>
                </ul>
            </li>
            <li><i class="fa-solid fa-chart-line"></i><strong>Pronostics :</strong>
                <ul>
                    <li>Avant le début de chaque match, les participants doivent soumettre leurs pronostics pour le résultat du match.</li>
                    <li>Les pronostics comprennent le score exact du match et le résultat (victoire, match nul, défaite) pour chaque équipe.</li>
                    <li>Les pronostics doivent être soumis avant l'heure de début officielle du match.</li>
                    <li>Le pronostic du gagnant final doit être défini pour le mardi 18 juin 2024 (dernier match du premier tour de la phase de groupe).
                </ul>
            </li>
            <li><i class="fa-solid fa-circle-up"></i><strong>Points :</strong>
                <ul>
                    <li>Les participants gagnent des points en fonction de l'exactitude de leurs pronostics.</li>
                    <li>Si un participant prédit correctement le score exact du match, il obtient 3 points.</li>
                    <li>Si un participant prédit correctement le résultat du match (victoire, match nul, défaite), il obtient 1 point.</li>
                    <li>Si un participant prédit correctement l'équipe finaliste gagnante, il obtient 10 points.</li>

                </ul>
            </li>
            <li><i class="fa-solid fa-ranking-star"></i><strong>Classement :</strong>
                <ul>
                    <li>Un classement individuel est établi en fonction du nombre de points accumulés par chaque participant tout au long de la compétition.</li>
                    <li>Un classement par équipe est établi en fonction du nombre total de points de ses membres, divisé par le nombre de membres dans l'équipe.</li>
                    <li>Le participant ou l'équipe avec le plus grand nombre de points à la fin de l'EURO 2024 est déclaré vainqueur.</li>
                </ul>
            </li>
            <li><i class="fa-solid fa-medal"></i><strong>Récompenses :</strong>
                <ul>
                    <li>Des récompenses peuvent être attribuées aux participants ayant obtenu les meilleurs résultats.</li>
                </ul>
            </li>
            <li><i class="fa-solid fa-scale-balanced"></i><strong>Fair-play et Respect :</strong>
                <ul>
                    <li>Les participants doivent respecter les autres joueurs et ne pas utiliser de langage offensant ou inapproprié sur la plateforme de pronostics.</li>
                    <li>Toute tentative de tricherie ou de manipulation des pronostics entraînera la disqualification immédiate du participant concerné.</li>
                </ul>
            </li>
        </ol>
        <p>En suivant ces règles, nous créons un environnement compétitif et amusant pour les amateurs de football lors de l'EURO 2024. Que le meilleur pronostiqueur gagne !</p>
</div>