config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }
  root "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :games, only: %i[index new create] do # /games GET user-games index, /games/new GET games new, /game/new POST games create
    resources :users_games, only: %i[new create edit update]
    resources :teams, only: [:index]
    resources :matches, only: [:index] do
      resources :pronostics, only: %i[create update]
    end
    member do
      get :dashboard
      get :ranking
#       get :join
    end
  end

  namespace :admin do 
    resources :matches, only: [:index, :new, :create, :edit, :update]
  end

  namespace :organisateur do
    resources :games, only: [:edit] do # /organisateur/games/edit
      resources :departments, only: [:create]
    end
  end
  
  resources :chats, only: :show do
    resources :messages, only: [:create]
  end

  get 'join_game/:code', to: 'games#join', as: :join_game
  get '/games/check_code', to: 'games#check_code', as: 'games_check_code'
  get '/games/change_game', to: 'games#change', as: :change_game

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :users_games, dependent: :destroy
  has_many :pronostics, dependent: :destroy
  has_many :users, through: :users_games
  has_many :departments, dependent: :destroy
  has_one :chat

validates :name, uniqueness: true

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    # @user_game = UsersGame.create!(user: current_user, game: @game, department: nil)
    # @organisator = User.find(user: current_user)
    @game.code = SecureRandom.urlsafe_base64(10)
    if @game.save
      Chat.create(name: @game.name, game: @game) # Créer un chat associé au jeu
      session[:game_code] = @game.code # Stocker le code dans la session
      redirect_to edit_organisateur_game_path(@game), notice: 'La partie a été créée avec succès.'
    else
      render :new
    end
  end

  def dashboard
    @dashboard = true
    @latest_pronostic = current_user.pronostics.order(updated_at: :desc).where.not(status: nil).first
    @game = Game.find(params[:id])
    @user_game = UsersGame.find_by(game: @game, user: current_user)
    @department = UsersGame.find_by(user: current_user, game: @game).department
    @owner = UsersGame.find_by(user: current_user, game: @game).owner
    if Match.exists?(params[:id])
      @match = Match.find(params[:id])
    else
      # donner une valeur par défaut:
      @match = Match.new
    end

    @dashboard_individual_rankings = UsersGame.joins(:user, :game, :department)
                                              .select('games.name, departments.name as team, users.pseudo, SUM(users_games.total_score) as total_score')
                                              .where('games.id = ?', @game)
                                              .group('games.name, users.id, team' )
                                              .order('total_score DESC')
                                              .limit(3)

    @dashboard_department_rankings = UsersGame.joins(:user, :game, :department)
                                         .select('departments.name as team, AVG(users_games.total_score) as average_score')
                                         .where('games.id = ?', @game)
                                         .group('team')
                                         .order('average_score DESC')
                                         .limit(3)

    @next_three_matches = Match.where("date > ?", Date.today).order(:date).limit(3).map do |match|
      prono = Pronostic.find_by(match: match, user: current_user)
      [match, prono]
    end
  end

  def ranking
    @game = Game.find(params[:id])
    @users_games = UsersGame.where(game_id: @game.id)

    if @users_games.present?
      @user_scores = Hash.new(0)

      @users_games.each do |user_game|
        @user_scores[user_game.user_id] += user_game.total_score.to_i
      end

      @users_ranking = @user_scores.sort_by { |_user_id, score| -score }.to_h.keys.map { |user_id| [User.find(user_id), @user_scores[user_id]] }
    else
      @users_ranking = []
    end
    @teamranking = teamranking
  end

  def join
    game_code = params[:code]
    session[:game_code] = game_code
    game = Game.find_by(code: params[:code])
    if game
      UsersGame.create(user: current_user, game: game)
      redirect_to dashboard_game_path(game), notice: 'Bienvenue! Vous avez bien rejoint la partie!'
    else
      redirect_to root_path, alert: 'Code Invalide.'
    end
  end

  def check_code
    @game = Game.find_by(code: params[:code])
    if UsersGame.exists?(user: current_user, game: @game)
      redirect_to dashboard_game_path(@game)
    elsif @game
      flash[:notice] = "Le code du jeu est valide."
      redirect_to new_game_users_game_path(@game)
    end
  end

  def change
    @usersgames = UsersGame.where(user_id: current_user)
    @games = @usersgames.map(&:game_id).uniq
    @games_names = Game.where(id: @games).pluck(:name)
  end

  private

  def teamranking
    @game = Game.find(params[:id])
    @users_games = @game.users_games
    @users = User.joins(:users_games).where(users_games: { id: @users_games }) # Utilisation de joins pour récupérer les utilisateurs associés au jeu
    @scores_by_department = Hash.new(0)
    @user_count_by_department = Hash.new(0)
    # Collecter les scores et compter les utilisateurs par département
    @users_games.each do |user_game|
      # department = user.users_games.department.to_sym
      department = user_game.department.name
      score = user_game.total_score # Somme des scores pour un utilisateur donné
      @scores_by_department[department] += score
      @user_count_by_department[department] += 1
    end
    # Diviser les scores par le nombre d'utilisateurs dans chaque département
    @scores_by_department.each_key do |department|
      @scores_by_department[department] /= @user_count_by_department[department].to_f
    end
    # Trier les scores par département en fonction de la moyenne (du plus haut au plus bas)
    @sorted_scores_by_department = @scores_by_department.sort_by { |department, score| -score }.to_h
  end

  def game_params
    params.require(:game).permit(:name, :user_id)
  end
end

app/controllers/organisateur/games_controller.rb
class Organisateur::GamesController < ApplicationController

  def edit
    @game = Game.find(params[:id])
    @game_departments = Department.where(game: @game)
    @department = Department.new
    @game_users = UsersGame.where(game: @game)
    @users = @game_users.map(&:user)
  end
end

app/views/games/change.html.erb
<%# path : join_game_path(:code) %>
<div class="container">
<div class="party">
    <h1>Choisir une partie</h1>
    <%= form_with url: change_game_path, class: "check-code", method: :get do |form| %>
      <%= form.select :game, options_for_select(@games_names, prompt: "Choisis une partie"), {}, { class: "form-control", label: false } %>
      <%= form.submit 'Valider', class: "signin-btn mt-3" %>
    <% end %>
    </div>
</div>

app/views/games/check_code.html.erb
<%# path : join_game_path(:code) %>
<div class="container">
<div class="party">
    <h1>Rejoindre une partie</h1>
    <%= form_with url: games_check_code_path, class: "check-code", method: :get do |f| %>
        <%= f.text_field :code, placeholder: "Entrez le code du jeu" %>
        <%= button_tag type: 'submit', id: "checkbtn" do %>
          <i class="fa-regular fa-square-check" aria-hidden="true"></i> Vérifier le code
        <% end %>
    <% end %>
    </div>
</div>

app/views/games/dashboard.html.erb
<div class="banner">
    <div class="container">
      <%# <%= render "shared/popup" %>
        <h1>Dashboard </h1>
        <div class="hello-flex">
         <h3 class="mt-2">Bonjour <%= current_user.pseudo %> 👋🏻</h3>
        </div>
        <div class="infos-flex">
          <ul>
            <li><strong>Partie -</strong> <%= @game.name %></li>
            <li><strong>Equipe -</strong> <%= @department.name %></li>
            <li><strong>Code -</strong> <%= @game.code %></li>
          </ul>
          <div>
            <% if Date.today > Date.new(2024, 6, 18) %>
              <h4>Equipe championne</h4>
              <%= @user_game.final_winner ? @user_game.final_winner.name : 'Aucune équipe sélectionnée' %>
            <% elsif @user_game.final_winner_id.nil? %>
              <%= render "shared/final-winner-form" %>
            <% else %>
              <h4>Mon prono</h4>
              <%# <%= @user_game.final_winner.name %>
              <%= render "shared/final-winner-form" %>
            <% end %>
          </div>
        </div>
        <div class="buttons-flex">
            <% if @owner == true %>
              <%= link_to(edit_organisateur_game_path(@game), class: "btn btn-test mb-2") do %>
              <i class="fa-regular fa-pen-to-square"></i> Editer la partie
              <% end %>
            <% end %>
        </div>

        <div class="performance-container">
          <p><strong> Mon dernier prono </strong></p>
            <div class="flex-perf">
              <div class="perf-category">
                <div class="perf-icon"><%= image_tag "v242_54.png", class: "avatar" %></div>
                <div class="perf-text">
                  <% if @latest_pronostic != nil %>
                    <% if @latest_pronostic.status == 'bonus'%>
                      + 4 points 
                    <% elsif @latest_pronostic.status == 'win'%>
                      + 2 point
                    <% else %>
                      + 0 point
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
        </div>
  </div>
</div>

        <div class="bottom-dashboard">
        <%= render "shared/ranking" %>
        <% if @next_three_matches %>
          <div class="dashboard-match">
          <h2 class="dashboard-match-title">DERNIERS MATCHS</h2>
          <% @next_three_matches.each do |match, prono| %>
            <%= render "shared/match", match: match, prono: prono %>
          <% end %></div>
        <% end %>
        </div>

app/views/games/new.html.erb
<div class="container">
  <div class="party">
    <h2>Créer une nouvelle partie</h2>
    <%= simple_form_for @game, local: true do |f| %>
      <%= f.text_field :name, :placeholder => 'Nom de la partie' %>
      <%= button_tag type: 'submit', id: "newgame" do %>
        <i class="fa-regular fa-square-plus" aria-hidden="true"></i> Créer la partie
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/ranking.html.erb
<% if @users_ranking.present? %>
  <div class="ranking-container">
    <h1>CLASSEMENT</h1>
    <div class="ranking-flex">
      <div class="ranking-category-left">
        <h2 class="title-cat-left">Individuel</h2>
        <div class="card-table">
        <table>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">PSEUDO</th>
              <th scope="col">EQUIPE</th>
              <th scope="col">POINTS</th>
            </tr>
          </thead>
        <tbody>
        <% @rang = 0 %>
            <% @users_ranking.each do |user, score| %>
              <tr>
                <th scope="row"><%= @rang += 1 %></th>
                <td><%= user.respond_to?(:pseudo) ? user.pseudo : user[0] %></td>
                <td><%= UsersGame.find_by(user: user).department.name %></td>
                <td><%= score %></td>
              </tr>
            <% end %>
        </tbody>
      </table>
      </div>
    </div>
      <div class="ranking-category-right">
        <h2 class="title-cat-right">Collectif</h2>
        <div class="card-table">
        <table>
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">EQUIPE</th>
              <th scope="col">POINTS</th>
            </tr>
          </thead>
          <tbody>
              <% @rang = 0 %>
              <% @sorted_scores_by_department.each do |department, score_average| %>
                <tr><th scope="row"><%= @rang += 1 %></th>
                  <td><%=department %></td>
                  <td>
                    <% if score_average % 1 == 0 %>
                      <%= score_average.to_i %>
                    <% else  %>
                      <%= score_average.round(1) %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>Aucune donnée de classement n'est disponible pour le moment.</p>
<% end %>
    </div>